name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
         - name: Get current time
           uses: 1466587594/get-current-time@v2
           id: current-time
           with:
                 format: YYYYMMDD-HH
                 utcOffset: "+08:00"

      
      
      
