name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
         - name: Get current time
           uses: 1466587594/get-current-time@v2
           id: current-time
           with:
                 format: YYYYMMDD-HH
                 utcOffset: "+08:00"
         - name: Use current time
           run: |
            TIME: "${{ steps.current-time.outputs.time }}"
            R_TIME: "${{ steps.current-time.outputs.readableTime }}"
            F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
            YEAR: "${{ steps.current-time.outputs.year }}"
            DAY: "${{ steps.current-time.outputs.day }}"
            run: echo $TIME $R_TIME $F_TIME $YEAR $DAY
      
      
      
